---
- name: Demo
  hosts: servera
  vars_files:
   - secret1.yml
   - secret2.yml
  tasks:
   - name: Print message1
     debug:
      msg: "{{pkg1}}"
   - name: Print message1
     debug:
      msg: "{{pkg2}}"
